-- Deploy demo:roles to pg

BEGIN;

CREATE ROLE joe LOGIN PASSWORD 'password';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA waddle TO joe;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA wisdom FROM joe;

CREATE ROLE jess LOGIN PASSWORD 'password';
GRANT ALL PRIVILEGES ON SCHEMA wisdom TO jess;
REVOKE ALL PRIVILEGES ON SCHEMA waddle FROM jess;
GRANT SELECT ON ALL TABLES IN SCHEMA wisdom TO jess;

GRANT USAGE ON SCHEMA joint to jess;
GRANT USAGE ON SCHEMA joint to joe;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA joint TO jess;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA joint TO joe;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA joint TO jess;
GRANT SELECT ON ALL TABLES IN SCHEMA joint TO joe;
GRANT INSERT ON ALL TABLES IN SCHEMA joint TO joe;
GRANT UPDATE ON ALL TABLES IN SCHEMA joint TO joe;

COMMIT;
