-- Deploy demo:roles to pg

BEGIN;

CREATE ROLE joe LOGIN PASSWORD 'password';
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA waddle TO joe;
-- REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA wisdom TO joe;

CREATE ROLE jess LOGIN PASSWORD 'password';
GRANT ALL PRIVILEGES ON SCHEMA wisdom TO jess;
REVOKE ALL PRIVILEGES ON SCHEMA waddle FROM jess;
GRANT SELECT ON ALL TABLES IN SCHEMA wisdom TO jess;

COMMIT;
